version: "3"
services:
    client:
        image: client
        ports:
          - "3000:3000"
        container_name: client_exam
        build:
            context: ./client
            dockerfile: Dockerfile
        environment:
            REACT_APP_API_URL: 'http://localhost:5000'
        
    server:
        image: server
        ports:
          - "5000:5000"
        container_name: server_exam
        build:
            context: ./server
            dockerfile: Dockerfile
        depends_on:
            - db
        environment:
            PORT: 5000
            DB_NAME: video_gallery
            DB_USER: mytestuser
            DB_PASSWORD: mypass
            DB_HOST: db
            DB_PORT: 5432
            SECRET_KEY: super_secret_key
        
    db:
        image: postgres
        ports:
            - "5434:5432"
        environment:
            POSTGRES_USER: mytestuser
            POSTGRES_PASSWORD: mypass
            POSTGRES_DB: video_gallery
            