CREATE DATABASE store;
\c store
CREATE TABLE store ( id serial PRIMARY KEY, name VARCHAR ( 50 ) UNIQUE NOT NULL, storeBudget INT);
CREATE TABLE store_product (StoreId SMALLINT NOT NULL,ProductId SMALLINT NOT NULL,sellingprice int);
CREATE TABLE product (id serial PRIMARY KEY, Name VARCHAR ( 50 ) UNIQUE NOT NULL, Description VARCHAR(150) NOT NULL);
CREATE TABLE customer (id SERIAL PRIMARY KEY,Name VARCHAR ( 50) NOT NULL,LastName VARCHAR ( 50) NOT NULL,Cash INT NOT NULL);
CREATE TABLE customerpurchases (CustomerId SMALLINT NOT NULL,StoreId SMALLINT NOT NULL,ProductId SMALLINT NOT NULL ,purchase_price );
CREATE TABLE factory(id SERIAL PRIMARY KEY,name VARCHAR(50) NOT NULL);
CREATE TABLE vendor(id SERIAL PRIMARY KEY,name VARCHAR(50),phone VARCHAR(12),email VARCHAR(25));
CREATE TABLE factory_product(factory_id SMALLINT,product_id SMALLINT,price int);
CREATE TABLE vendor_factory(vendor_id SMALLINT,factory_id SMALLINT,product_id SMALLINT,supplyprice INT);

INSERT INTO store(storename,storebudget) values('VipXanut', 500000);
INSERT INTO store(storename,storebudget) values('Erebuni', 750000);
INSERT INTO store(storename,storebudget) values('Nairi', 1500000);
INSERT INTO product(ProductName,Description) values('Xndzor','Qaxcr xndzor');
INSERT INTO product(ProductName,Description) values('Dzmeruk','yntir dzmeruk');
INSERT INTO product(ProductName,Description) values('Malina','Antari Malina');
INSERT INTO store_product(StoreId,productid,sellingprice) values(1,1,150);
INSERT INTO store_product(StoreId,productid,sellingprice) values(1,2,165);
INSERT INTO store_product(StoreId,productid,sellingprice) values(1,3,145);
INSERT INTO store_product(StoreId,productid,sellingprice) values(2,2,140);
INSERT INTO store_product(StoreId,productid,sellingprice) values(2,3,125);
INSERT INTO store_product(StoreId,productid,sellingprice) values(3,1,115);
INSERT INTO store_product(StoreId,productid,sellingprice) values(3,2,145);
INSERT INTO customer(customername,customerlastname,customercash) values('Mher', 'Araqelyan',250000);
INSERT INTO customer(customername,customerlastname,customercash) values('Aram', 'Armenakyan',150000);
INSERT INTO customer(customername,customerlastname,customercash) values('Tigran', 'Sahakyan',30000);
INSERT INTO customerpurchases(customerid,storeid,productid,purchase_price) values(1, 1, 1,150);
INSERT INTO customerpurchases(customerid,storeid,productid,purchase_price) values(1, 1, 3,145);
INSERT INTO customerpurchases(customerid,storeid,productid,purchase_price) values(2, 1, 1,150);
INSERT INTO customerpurchases(customerid,storeid,productid,purchase_price) values(3, 3, 2,145);
INSERT INTO factory(name) values('Berqarat');
INSERT INTO factory(name) values('Fruits');
INSERT INTO factory(name) values('Martuni');
INSERT INTO vendor(name,phone,email) values('Arman','095485868','aaa@mail.ru');
INSERT INTO vendor(name,phone,email) values('Varazdat','091845868','bbb@mail.ru');
INSERT INTO vendor(name,phone,email) values('Liparit','045654123','ccc@mail.ru');
INSERT INTO factory_product(factory_id,product_id,price) values (1,1,55);
INSERT INTO factory_product(factory_id,product_id,price) values (1,2,45);
INSERT INTO factory_product(factory_id,product_id,price) values (2,3,75);
INSERT INTO vendor_factory (vendor_id,factory_id,product_id,supplyprice) values (1,1,1,85);
INSERT INTO vendor_factory (vendor_id,factory_id,product_id,supplyprice) values (1,1,2,95);
INSERT INTO vendor_factory (vendor_id,factory_id,product_id,supplyprice) values (1,2,3,105);
alter table vendor_factory add constraint fk_vendor_factory_vendor foreign key (vendor_id) references vendor(id);
alter table vendor_factory add constraint fk_factory_fid foreign key (factory_id) references factory(id);
alter table vendor_factory add constraint fk_product_pid foreign key (product_id) references product(id);
alter table factory_product add constraint fk_factory_fid foreign key (factory_id) references factory(id);
alter table factory_product add constraint fk_product_pid foreign key (product_id) references product(id);
alter table store_product  add constraint fk_product_pid foreign key (productid) references product(id);
alter table store_product  add constraint fk_store_sid foreign key (storeid) references store(id);
alter table customerpurchases  add constraint fk_customer_cid foreign key (customerid) references customer(id);
alter table customerpurchases  add constraint fk_store_sid foreign key (storeid) references store(id);
alter table customerpurchases  add constraint fk_product_pid foreign key (productid) references product(id);
ALTER TABLE vendor add constraint check_email CHECK (email ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$');
CREATE TABLE unit (id SERIAL PRIMARY KEY,meas_unit VARCHAR (5) );
insert into unit(meas_unit) values('kg');
insert into unit(meas_unit) values('liter');
ALTER TABLE product  ADD COLUMN unit_id SMALLINT;
UPDATE product  SET unit_id = 1  WHERE id = 1 ;
UPDATE product  SET unit_id = 1  WHERE id = 2 ;
UPDATE product  SET unit_id = 1  WHERE id = 3 ;
alter table product add constraint fk_unit_uid foreign key (unit_id) references unit(id);

